---
title: "HW1_Task1"
author: "Corinna Hong"
date: "January 29, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

```{r, load packages}

library(tidyverse)
library(kableExtra)
library(janitor)

```

```{r, read in data}

showshoe_hares <- read_csv("showshoe_lter.csv")

```

```{r}

unique(showshoe_hares$sex) # check unique values of `sex` column in original data

hares_wrangle <- showshoe_hares %>% 
  filter(!is.na(sex)) %>% # remove NAs in sex column %>% 
  mutate(sex = str_to_upper(sex)) %>% 
  filter(sex %in% c("M", "F"))  %>% # look for anything in sex column matching "M" or "F" This is how I am getting rid of "?" and "PF"
  filter(!is.na(weight)) # remove NAs in weight column

unique(hares_wrangle$sex) # check unique values of 'sex' column in wrangled data

```

```{r, plot data, fig.align = 'center'}

hare_boxplot <- ggplot(hares_wrangle, aes(x = sex, y = weight)) +
  geom_boxplot() +
  geom_jitter(width = 0.1, alpha = 0.3, aes(color = sex)) + # Width of jitter, opacity(alpha) of dots, color coding by sex
  theme_classic() +
  labs (x = "Sex", y = "Body weight (g)", color = "Sex", title = "Box-and-Whisker Plot with Overlying Jitter of Showshoe Hare Body Mass")

hare_boxplot

```

```{r, summary statistics}

hares_summary <- hares_wrangle %>% 
  group_by(sex) %>% 
  summarize(
    mean = round(mean(weight), 2),
    sd = round(sd(weight), 2),
    n = length(sex)
  )

```

```{r, finalize table}

hares_table <- kable(hares_summary, caption = "Summary Table of Showshoe Hares", 
                     col.names = c("Sex","Mean Weight (g)","Standard Deviation (g)","Sample Size")) %>% # rename columns
  kable_styling(full_width = F, position = "center") # Decrease table width and centers it

hares_table

```

